# Generated by Django 5.0.6 on 2024-06-09 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'reviews'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='descricao',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='foto_empresa',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='fotos/'),
            preserve_default=False,
        ),
    ]
