# Generated by Django 5.0.6 on 2024-06-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='foto_empresa',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
